"""
LangChain ChatGPT Tool
----------------------
This module demonstrates how to create a ChatGPT tool using LangChain (langchain_openai).
Step-by-step comments are included to help you learn LangChain tool building!
"""

# STEP 1: Import required modules from LangChain and dotenv
import os
from dotenv import load_dotenv
from langchain_openai import ChatOpenAI
from langchain_core.tools import tool

# STEP 2: Load environment variables (API Key from .env file)
try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    pass


# STEP 3: Initialize the ChatOpenAI LLM model
# The API key can be explicitly passed or automatically picked up from OPENAI_API_KEY env variable.
api_key = os.getenv("OPENAI_API_KEY")
llm = ChatOpenAI(model="gpt-3.5-turbo", temperature=0.7, api_key=api_key)



# STEP 4: Define a LangChain Tool using the @tool decorator
# The docstring below is used by LangChain agents to understand what the tool does!
@tool
def ask_chatgpt(query: str) -> str:
    """Ask ChatGPT a question or request assistance with a prompt.
    
    Args:
        query (str): The prompt or question to send to ChatGPT.
        
    Returns:
        str: The response text generated by ChatGPT.
    """
    # Invoke the LLM model with the prompt
    response = llm.invoke(query)
    # Extract the text content from the response message object
    return response.content


# STEP 5: Runnable code for testing the file directly
if __name__ == "__main__":
    print("--- LangChain ChatGPT Tool Demo ---")
    
    # Check if OPENAI_API_KEY is configured
    api_key = os.getenv("OPENAI_API_KEY")
    if not api_key or api_key == "your_openai_api_key_here":
        print("[WARNING] OPENAI_API_KEY is not set or using placeholder in .env file.")
        print("Please update your .env file with a valid OpenAI API Key to invoke the model.")
    else:
        sample_prompt = "Hello, how are you?"
        print(f"\nSending Prompt: '{sample_prompt}'")
        
        # Test 1: Direct LLM invocation
        res = llm.invoke(sample_prompt)
        print(f"Direct Response: {res.content}\n")
        
        # Test 2: Calling via LangChain @tool
        tool_res = ask_chatgpt.invoke({"query": sample_prompt})
        print(f"Tool Output: {tool_res}")
