"""
LangChain Google Gemini LLM Tool
--------------------------------
This module demonstrates how to connect to Google Gemini using LangChain (langchain-google-genai).
Step-by-step comments are included to help you learn!
"""

# STEP 1: Import required modules from LangChain and dotenv
import os
try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    pass

try:
    from langchain_google_genai import ChatGoogleGenerativeAI
except ImportError:
    ChatGoogleGenerativeAI = None

from langchain_core.tools import tool

# STEP 2: Retrieve GOOGLE_API_KEY from environment variables
google_api_key = os.getenv("GOOGLE_API_KEY")

# STEP 3: Initialize the Gemini LLM model
# Available Model options:
# - "gemini-1.5-flash" (Fast, free tier)
# - "gemini-1.5-pro"   (Advanced reasoning)
# - "gemini-2.0-flash" (Latest Gemini model)
if ChatGoogleGenerativeAI and google_api_key and "your_" not in google_api_key:
    gemini_llm = ChatGoogleGenerativeAI(
        model="gemini-1.5-flash",  # Official valid Gemini model
        temperature=0.7,
        google_api_key=google_api_key
    )



else:
    gemini_llm = None


# STEP 4: Define a LangChain Tool using the @tool decorator
@tool
def ask_gemini(query: str) -> str:
    """Ask Google Gemini LLM a question or request assistance.
    
    Args:
        query (str): The prompt or question to send to Gemini.
        
    Returns:
        str: The response text generated by Gemini.
    """
    if not gemini_llm:
        return "Gemini LLM is not initialized. Please ensure GOOGLE_API_KEY is configured in .env."
    response = gemini_llm.invoke(query)
    return response.content


# STEP 5: Runnable code for testing the file directly
if __name__ == "__main__":
    print("--- LangChain Google Gemini LLM Demo ---")
    
    if not google_api_key or "your_" in google_api_key:
        print("[WARNING] GOOGLE_API_KEY is missing or set to placeholder in .env file.")
        print("Get a free Gemini API key at: https://aistudio.google.com")
    elif not ChatGoogleGenerativeAI:
        print("[WARNING] langchain-google-genai package is not installed.")
        print("Please run: pip install langchain-google-genai")
    else:
        sample_prompt = "Hello Gemini, explain AI agents in one sentence!"
        print(f"\nSending Prompt: '{sample_prompt}'")
        res = gemini_llm.invoke(sample_prompt)
        print(f"\nDirect Gemini Response:\n{res.content}")
