"""
LangChain Grok (xAI) LLM Tool
------------------------------
This module demonstrates how to connect to xAI's Grok LLM using LangChain.
Since xAI provides an OpenAI-compatible API, we use ChatOpenAI pointing to https://api.x.ai/v1.
"""

# STEP 1: Import required modules
import os
try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    pass

from langchain_openai import ChatOpenAI
from langchain_core.tools import tool

# STEP 2: Retrieve the xAI API Key from environment variables
xai_api_key = os.getenv("XAI_API_KEY")

# STEP 3: Initialize the Grok LLM model using ChatOpenAI with xAI base URL
# xAI endpoint: https://api.x.ai/v1
# Supported Models: grok-2-latest, grok-beta
grok_llm = ChatOpenAI(
    model="grok-2-latest",
    temperature=0.7,
    api_key=xai_api_key,
    base_url="https://api.x.ai/v1"
)


# STEP 4: Create a LangChain tool wrapper around Grok
@tool
def ask_grok(query: str) -> str:
    """Ask xAI's Grok LLM a question or request reasoning assistance.
    
    Args:
        query (str): The prompt or question to send to Grok.
        
    Returns:
        str: The response text generated by Grok.
    """
    response = grok_llm.invoke(query)
    return response.content


# STEP 5: Runnable code for testing the file directly
if __name__ == "__main__":
    print("--- LangChain Grok (xAI) LLM Demo ---")
    
    if not xai_api_key or xai_api_key == "your_xai_api_key_here":
        print("[WARNING] XAI_API_KEY is not set or using placeholder in .env file.")
        print("Please update your .env file with a valid xAI API Key to invoke Grok.")
    else:
        sample_prompt = "Hello Grok, tell me a quick fun fact about space!"
        print(f"\nSending Prompt: '{sample_prompt}'")
        
        # Test 1: Direct Grok LLM invocation
        res = grok_llm.invoke(sample_prompt)
        print(f"\nDirect Grok Response:\n{res.content}\n")
        
        # Test 2: Calling via LangChain @tool
        tool_res = ask_grok.invoke({"query": sample_prompt})
        print(f"Tool Output:\n{tool_res}")
